import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" antialiased flex flex-col h-dvh justify-center items-center bg-linear-to-r from-[#ff75c3] via-[#ffa647] to-[#ffe3ff]"
      >
        {children}
      </body>
    </html>
  );
}
